force-app/main/default/objects/Agenda__c/Agenda__c.object-meta.xml
<CustomObject>
    <label>Agenda</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de la Agenda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agenda__c/fields/Centro__c.field-meta.xml
<CustomField>
    <fullName>Centro__c</fullName>
    <label>Centro</label>
    <referenceTo>Centro__c</referenceTo>
    <relationshipLabel>Agendas</relationshipLabel>
    <relationshipName>Agendas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Dias_Disponibles__c.field-meta.xml
<CustomField>
    <fullName>Dias_Disponibles__c</fullName>
    <label>Dias Disponibles</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lunes</fullName>
            </value>
            <value>
                <fullName>Martes</fullName>
            </value>
            <value>
                <fullName>Miércoles</fullName>
            </value>
            <value>
                <fullName>Jueves</fullName>
            </value>
            <value>
                <fullName>Viernes</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Especialidad__c.field-meta.xml
<CustomField>
    <fullName>Especialidad__c</fullName>
    <label>Especialidad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Especialidad__c.Centro__c</field>
            <operation>equals</operation>
            <valueField>$Source.Centro__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Especialidad__c</referenceTo>
    <relationshipLabel>Agendas</relationshipLabel>
    <relationshipName>Agendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Fecha_Final__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Final__c</fullName>
    <label>Fecha Final</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Fecha_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio__c</fullName>
    <label>Fecha Inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Hora_Final_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Hora_Final_Agenda__c</fullName>
    <defaultValue>TIMEVALUE(&quot;18:00:00.000&quot;)</defaultValue>
    <label>Hora Final Agenda</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Agenda__c/fields/Hora_Inicio_Agenda__c.field-meta.xml
<CustomField>
    <fullName>Hora_Inicio_Agenda__c</fullName>
    <defaultValue>TIMEVALUE(&quot;9:30:00.000&quot;)</defaultValue>
    <label>Hora Inicio Agenda</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Centro__c/Centro__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registrar los centros mérdicos que ofrecerán servicios en nuestra plataforma.</description>
    <label>Centro</label>
    <nameField>
        <label>Nombre del Centro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Especialidad__c/Especialidad__c.object-meta.xml
<CustomObject>
    <label>Especialidad</label>
    <nameField>
        <label>Nombre de la Especialidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Especialidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Especialidad__c/fields/Centro__c.field-meta.xml
<CustomField>
    <fullName>Centro__c</fullName>
    <label>Centro</label>
    <referenceTo>Centro__c</referenceTo>
    <relationshipLabel>Especialidades</relationshipLabel>
    <relationshipName>Especialidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Especialidad__c/fields/Especialista__c.field-meta.xml
<CustomField>
    <fullName>Especialista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Especialista</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Especialista</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Especialidades</relationshipLabel>
    <relationshipName>Especialidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AgendadoCitasHelper.cls
public with sharing class AgendadoCitasHelper {
    @InvocableMethod(label='Recuperar Slots de Citas' description='Calcula los slots disponibles para el día, centro y especialidad seleccionados')
    public static List<List<String>> getSlotsFromAgendas(List<RequestData> requests) {
        
        List<List<String>> result = new List<List<String>>();

        RequestData req = requests[0];        

        Date fechaCita = req.fechaCita;
        String idCentro = req.idCentro;
        String idEspecialidad = req.idEspecialidad;
        String idEspecialista = req.idEspecialista;

        String query = 'SELECT Id, Hora_Inicio_Agenda__c, Hora_Final_Agenda__c ' +
               'FROM Agenda__c ' +
               'WHERE Dias_Disponibles__c INCLUDES (\'' + String.escapeSingleQuotes(req.diaDeLaSemana) + '\') ' +
               'AND Fecha_Inicio__c <= :fechaCita ' +
               'AND Fecha_Final__c >= :fechaCita ' +
               'AND Centro__c = :idCentro ' +
               'AND Especialidad__c = :idEspecialidad';

        List<Event> eventosExistentes = [SELECT Id, StartDateTime 
                                            FROM Event 
                                            WHERE (Especialidad__r.Especialista__c =: idEspecialista OR Especialidad__c =: idEspecialidad) AND ActivityDate = :fechaCita];
        Set<String> horasOcupadas = new Set<String>();
        for (Event ev : eventosExistentes) {
            if (ev.StartDateTime != null) {
                horasOcupadas.add(ev.StartDateTime.format('HH:mm'));
            }
        }
      
        List<Agenda__c> agendas = Database.query(query);
        for (Agenda__c agenda : agendas) {
            List<String> slots = new List<String>();
            Time startTime = agenda.Hora_Inicio_Agenda__c;
            Time endTime = agenda.Hora_Final_Agenda__c;
            while (startTime < endTime) {
                String slotStr = String.valueOf(startTime).substring(0, 5);
                // Solo añade el slot si no está ocupado
                if (!horasOcupadas.contains(slotStr)) {
                    slots.add(slotStr);
                }
                startTime = startTime.addMinutes(15);
            }
            result.add(slots);
        }
        return result;
    }

    public class RequestData {
        @InvocableVariable public String diaDeLaSemana;
        @InvocableVariable public Date fechaCita;
        @InvocableVariable public String idCentro;
        @InvocableVariable public String idEspecialidad;
        @InvocableVariable public String idEspecialista;
    }
}